/* ==========================================================================
   Loads reports.json (auto-generated by the GitHub Action from whatever
   PDFs exist in /reports) and provides small lookup helpers. Every page
   that needs the report list calls loadReports() once.
   ========================================================================== */

async function loadReports() {
  try {
    // Root-relative, not "reports.json": 404.html is served at whatever URL
    // the visitor mistyped, so a relative path would resolve against that.
    const res = await fetch("/reports.json", { cache: "no-store" });
    if (!res.ok)
      throw new Error("reports.json not found (status " + res.status + ")");
    return await res.json();
  } catch (err) {
    console.error("Could not load reports.json:", err);
    return [];
  }
}

function findReport(reports, slug) {
  return reports.find(function (r) {
    return r.slug === slug;
  });
}

// reports[] is sorted newest-first by the generator script.
function getAdjacent(reports, slug) {
  const index = reports.findIndex(function (r) {
    return r.slug === slug;
  });
  return {
    newer: index > 0 ? reports[index - 1] : null,
    older: index >= 0 && index < reports.length - 1 ? reports[index + 1] : null,
  };
}
