/* ==========================================================================
   Loads survey.json (auto-generated by the GitHub Action from whatever
   PDFs exist in /survey). Only the title/period label is automated this
   way — the actual stats, charts, and takeaways on community-pulse.html
   still need manual updates each survey cycle (see comment at the top of
   that file).
   ========================================================================== */

async function loadSurveys() {
  try {
    // Root-relative for the same reason as reports-loader.js.
    const res = await fetch("/survey.json", { cache: "no-store" });
    if (!res.ok)
      throw new Error("survey.json not found (status " + res.status + ")");
    return await res.json();
  } catch (err) {
    console.error("Could not load survey.json:", err);
    return [];
  }
}
